# Generated by Django 2.1.1 on 2018-09-26 08:45

import blog.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180925_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_nb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(upload_to=blog.services.file_rename, verbose_name='Photo'),
        ),
    ]
